### ISSUE TITLE
Permission to use "Choosing A Good Chart

### ISSUE THREAD

**Issue by brymz** [swcarpentry/visualization-novice#16]
I found two instances where Dr. Andrew Abela gave permission to reuse his "Choosing a Good Chart" graphic. Do we want to pursue getting his permission for this lesson?

- https://community.qlik.com/docs/DOC-7816
- http://www.juiceanalytics.com/writing/introducing-chart-chooser-v2

**Comment by gvwilson** [comment]
I believe I have it, but I'm damned if I can find the email - please 
give him a shout and confirm.

**Comment by brymz** [comment]
From Andrew Abela via email 12/27/2016:

> Yes, you have my permission. Please cite the following work:
> 
> [https://www.amazon.com/Advanced-Presentations-Design-Creating-Communication/dp/1118347919/ref=asap_bc?ie=UTF8](https://www.amazon.com/Advanced-Presentations-Design-Creating-Communication/dp/1118347919/ref=asap_bc?ie=UTF8)

**Comment by brymz** [comment]
Closed by https://github.com/swcarpentry/visualization-novice/pull/15/commits/3c19c963c017376f73317eaa66cc4c2aa39f761b
