### ISSUE TITLE
Generate summative assessment solution

### ISSUE THREAD

**Issue by brymz** [swcarpentry/visualization-novice#2]
Four figures with [Gapminder data](https://www.gapminder.org/data/)
- Line histogram - single variable distribution with many data points
- Bubble chart - relationship with three variables
- Faceted bar chart - comparison among many items/categories
- Stacked column/area chart - composition changing over time

**Comment by gvwilson** [comment]
Nice - can you do two versions of each (one bad and one good)?  Johnson's [GUI Bloopers](https://www.amazon.com/GUI-Bloopers-2-0-Second-Technologies/dp/0123706432/), which is the best book I ever read on user interface design, takes this approach: he says he can't tell us how to design a good interface, but he can tell us how to critique and fix a bad one.
